name: Update README Date

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update README date
        run: |
          today=$(date '+%Y-%m-%d')
          # 「最終更新日: 」で始まる行を今日の日付に書き換え
          sed -i "s/^最終更新日: .*/最終更新日: $today/" README.md

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          # 変更がある場合だけコミット
          git diff --cached --quiet || git commit -m "Update 最終更新日 in README.md"
          git push
